markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: uazw blog
host: uazw.github.com
desc: saying........

custom:
    category:
        default: Default Category
        schema_less: Schema-Less
    categories:
      - name:  default
        title: Default Category

      - name:  schema_less
        title: Schema-Less

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: uazw
        email: wy19940528@gmail.com
        disqus: your-disqus-short-name              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: uazw                # GitHub账号
        gravatar: 3f0b83fdfbbdb9c42810ef046d73f408  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
